version: "3.9"

services:
  refine-project:
    build: "./"
    command: ["serve", "refine-project"]
    ports:
      - "80:80"
  other-refine-project:
    build: "./"
    command: ["serve", "other-refine-project"]
    ports:
      - "81:80"
  keycloak:
    command: [ "start-dev" ]
    image: quay.io/keycloak/keycloak:21.0.0
    volumes:
        - ./runtime/keycloak:/opt/keycloak/data/
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
        - "8080:8080"